name: libft

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test with libft-unit-test on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Add so to Makefile
      uses: DamianReeves/write-file-action@master
      with:
        path: Makefile
        contents: |
          so:
            $(CC) -nostartfiles -fPIC $(CFLAGS) $(SRC)
            gcc -nostartfiles -shared -o libft.so $(OBJ)
        write-mode: append
    - name: Download tests repo
      run: |
        cd ..
        git clone https://github.com/alelievr/libft-unit-test.git libft-unit-test
    - name: Run tests
      run: |
        cd libft-unit-test
        make
            
