name: libft

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test with libft-unit-test on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Add so to Makefile
      run: echo -e "so:\n\t\t\t\$(CC) -nostartfiles -fPIC \$(FLAGS) \$(SRCS) \$(BONUS_SRCS)\n\t\t\tgcc -nostartfiles -shared -o libft.so \$(OBJS) \$(BONUS_OBJS)\n" | sed '84r /dev/stdin' Makefile > temp && mv temp Makefile
    - name: Install libbsd-dev
      run: sudo apt-get install -y libbsd-dev
    - name: Download tests repo
      run: |
        cd ..
        git clone https://github.com/alelievr/libft-unit-test.git libft-unit-test
    - name: Build tests
      run: |
        cd ..
        cd libft-unit-test
        make
    - name: Run tests
      run: |
        cd ..
        cd libft-unit-test
        ./run_test
